/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.loaisanphamBLL;
import DAL.LoaiSanPham;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows
 */
public class Category extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        loadDataToTable();
    }

private void loadDataToTable() {
    try {
         TableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "maloai", "tenloai"
            }
        ));
        loaisanphamBLL dao = new loaisanphamBLL();
        List<LoaiSanPham> list = dao.getAllCategory();
          System.out.println(list.size());
        DefaultTableModel model = (DefaultTableModel) TableCategory.getModel();
        model.setRowCount(0); 
        for (LoaiSanPham b : list) {
        System.out.println(b); // In ra Book nhờ toString()
        model.addRow(new Object[]{
        b.getMaLoai(), b.getTenLoai()
        });
    }
    } catch  (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi load dữ liệu!");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCategory = new javax.swing.JTable();
        CategoryID = new javax.swing.JTextField();
        AddCategory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NameCategory = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        UpdateCategory = new javax.swing.JButton();
        DeleteCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Category");

        TableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCategory);

        CategoryID.setEnabled(false);

        AddCategory.setBackground(new java.awt.Color(51, 153, 255));
        AddCategory.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        AddCategory.setText("Add Category");
        AddCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCategoryMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel2.setText("Name Category");

        NameCategory.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel3.setText("CategoryID");

        UpdateCategory.setBackground(new java.awt.Color(204, 204, 0));
        UpdateCategory.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        UpdateCategory.setText("Update Category");
        UpdateCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateCategoryMouseClicked(evt);
            }
        });

        DeleteCategory.setBackground(new java.awt.Color(204, 0, 0));
        DeleteCategory.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        DeleteCategory.setText("Delete Category");
        DeleteCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteCategoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addGap(216, 216, 216))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CategoryID, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                            .addComponent(NameCategory))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(AddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UpdateCategory)))
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(DeleteCategory)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UpdateCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCategoryMouseClicked
        // TODO add your handling code here:
         try{        
        loaisanphamBLL categoryBLL = new loaisanphamBLL();
        LoaiSanPham categoryDAL = new LoaiSanPham(0,NameCategory.getText());
        boolean isSuccess= categoryBLL.insertCategory( categoryDAL);
          if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
            loadDataToTable();
          } else {
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!");
          }
        }
        catch (HeadlessException | NumberFormatException | SQLException e) {
         JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL: " + e.getMessage());
        }
    }//GEN-LAST:event_AddCategoryMouseClicked

    private void UpdateCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateCategoryMouseClicked
        // TODO add your handling code here:
             loaisanphamBLL categoryBLL = new loaisanphamBLL();
        try{
             LoaiSanPham categoryDAL = new LoaiSanPham(Integer.parseInt(CategoryID.getText()),NameCategory.getText());
            boolean isSuccess = categoryBLL.updateCategory(categoryDAL);
            if(isSuccess) {
                JOptionPane.showMessageDialog(this, "Sửa sản phầm thành công!");
                loadDataToTable(); // reload lại dữ liệu lên bảng
            } else {
                JOptionPane.showMessageDialog(this, "Sửa sản phầm  thất bại!");
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá tiền hoặc số lượng không hợp lệ!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa sách: " + e.getMessage());
            e.printStackTrace();
        }
        loadDataToTable();
    }//GEN-LAST:event_UpdateCategoryMouseClicked

    private void DeleteCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteCategoryMouseClicked
        // TODO add your handling code here:
            loaisanphamBLL categoryBLL = new loaisanphamBLL();
        try{
            boolean isSuccess = categoryBLL.deleteCategory(Integer.parseInt(CategoryID.getText()));
            if(isSuccess) {
                JOptionPane.showMessageDialog(this, "Xóa loại sản phẩm thành công!");
                loadDataToTable(); // reload lại dữ liệu lên bảng
            } else {
                JOptionPane.showMessageDialog(this, "Xóa loại sản phầm  thất bại!");
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá trị xóa không hợp lệ ");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa loại sản phẩm: " + e.getMessage());
            e.printStackTrace();
        }
        loadDataToTable();
    }//GEN-LAST:event_DeleteCategoryMouseClicked

    private void TableCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCategoryMouseClicked
        // TODO add your handling code here:
        int selectedRow = TableCategory.getSelectedRow();
        if (selectedRow >= 0) {
             DefaultTableModel model = (DefaultTableModel) TableCategory.getModel();
                String categorytId = model.getValueAt(selectedRow, 0).toString(); 
                String nameCategory = model.getValueAt(selectedRow, 1).toString(); 
                CategoryID.setText(categorytId);
                NameCategory.setText(nameCategory);
        }
    }//GEN-LAST:event_TableCategoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCategory;
    private javax.swing.JTextField CategoryID;
    private javax.swing.JButton DeleteCategory;
    private javax.swing.JTextField NameCategory;
    private javax.swing.JTable TableCategory;
    private javax.swing.JButton UpdateCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
