/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Windows
 */
public class Home extends javax.swing.JFrame {
     
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();}
//        ImageLabel.setIcon(resizeImage("D:\\DuAnMonJava\\ManageJava\\JavaApplication2\\src\\icon\\fine-home-interior-living-room-picture-wallpaper-2560x1080_14.jpg", 654, 300));
//ImageLabel.setText("");
// linkProduct.addMouseListener(new java.awt.event.MouseAdapter() {
//    @Override
//    public void mouseEntered(java.awt.event.MouseEvent evt) {
//        linkProduct.setOpaque(true);  // phải bật opaque để đổi màu nền
//        linkProduct.setBackground(new Color(100, 149, 237)); // màu xanh nhạt
//        linkProduct.setForeground(Color.WHITE); // đổi màu chữ
//    }
//
//    @Override
//    public void mouseExited(java.awt.event.MouseEvent evt) {
//        linkProduct.setOpaque(false);
//        linkProduct.setBackground(new Color(204, 204, 204)); // màu nền cũ của panel
//        linkProduct.setForeground(Color.BLACK); // màu chữ mặc định
//    }
//});
//   linkCategory1.addMouseListener(new java.awt.event.MouseAdapter() {
//    @Override
//    public void mouseEntered(java.awt.event.MouseEvent evt) {
//        linkCategory1.setOpaque(true);
//        linkCategory1.setBackground(new Color(100, 149, 237));
//        linkCategory1.setForeground(Color.WHITE);
//    }
//
//    @Override
//    public void mouseExited(java.awt.event.MouseEvent evt) {
//        linkCategory1.setOpaque(false);
//        linkCategory1.setBackground(new Color(204, 204, 204));
//        linkCategory1.setForeground(Color.BLACK);
//    }
//});
//   linkCategory.addMouseListener(new java.awt.event.MouseAdapter() {
//    @Override
//    public void mouseEntered(java.awt.event.MouseEvent evt) {
//        linkCategory.setOpaque(true);
//        linkCategory.setBackground(new Color(100, 149, 237));
//        linkCategory.setForeground(Color.WHITE);
//    }
//
//    @Override
//    public void mouseExited(java.awt.event.MouseEvent evt) {
//        linkCategory.setOpaque(false);
//        linkCategory.setBackground(new Color(204, 204, 204));
//        linkCategory.setForeground(Color.BLACK);
//    }
//});
//   linkCategory2.addMouseListener(new java.awt.event.MouseAdapter() {
//    @Override
//    public void mouseEntered(java.awt.event.MouseEvent evt) {
//        linkCategory2.setOpaque(true);
//        linkCategory2.setBackground(new Color(100, 149, 237));
//        linkCategory2.setForeground(Color.WHITE);
//    }
//
//    @Override
//    public void mouseExited(java.awt.event.MouseEvent evt) {
//        linkCategory2.setOpaque(false);
//        linkCategory2.setBackground(new Color(204, 204, 204));
//        linkCategory2.setForeground(Color.BLACK);
//    }
//});
//    }
//private ImageIcon resizeImage(String imagePath, int width, int height) {
//    ImageIcon originalIcon = new ImageIcon(imagePath);
//    Image img = originalIcon.getImage();
//    Image resizedImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
//    return new ImageIcon(resizedImg);
//}
//
//   private ImageIcon resizeIcon(String path, int width, int height) {
//        // Lấy ảnh từ resource folder
//        ImageIcon icon = new ImageIcon(getClass().getResource(path));
//        Image img = icon.getImage();
//        Image resizedImage = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
//        return new ImageIcon(resizedImage);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        linkProduct = new javax.swing.JLabel();
        linkCategory = new javax.swing.JLabel();
        linkCategory1 = new javax.swing.JLabel();
        linkCategory2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 45, 101));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÍ CỬA HÀNG NỘI THẤT THÔNG MINH ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        linkProduct.setBackground(new java.awt.Color(33, 47, 61));
        linkProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        linkProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkProduct.setText("Sản phẩm");
        linkProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkProductMouseClicked(evt);
            }
        });

        linkCategory.setBackground(new java.awt.Color(33, 47, 61));
        linkCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        linkCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkCategory.setText("Nhập hàng");
        linkCategory.setToolTipText("");
        linkCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkCategoryMouseClicked(evt);
            }
        });

        linkCategory1.setBackground(new java.awt.Color(33, 47, 61));
        linkCategory1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        linkCategory1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkCategory1.setText("Danh mục ");

        linkCategory2.setBackground(new java.awt.Color(33, 47, 61));
        linkCategory2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        linkCategory2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkCategory2.setText("Phiếu nhập");
        linkCategory2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkCategory2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linkProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(linkCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(linkCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(linkCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(linkCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(linkCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(linkCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, -1, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ngoc\\OneDrive\\Pictures\\home.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
  private void openForm(JFrame currentFrame, JFrame newForm) {
    currentFrame.setVisible(false);
    newForm.setVisible(true);
    newForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    newForm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            currentFrame.setVisible(true);
        }
    });
            }
    private void linkProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkProductMouseClicked
        // TODO add your handling code here:\
         openForm(this, new Product());
    }//GEN-LAST:event_linkProductMouseClicked

    private void linkCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCategoryMouseClicked
        try {
            // TODO add your handling code here:
            openForm(this, new NhapHang());
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_linkCategoryMouseClicked

    private void linkCategory2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkCategory2MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            openForm(this, new PhieuNhapGUI());
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_linkCategory2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
              FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel linkCategory;
    private javax.swing.JLabel linkCategory1;
    private javax.swing.JLabel linkCategory2;
    private javax.swing.JLabel linkProduct;
    // End of variables declaration//GEN-END:variables
}
